# coding: utf-8
source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'
# https://gems.ruby-china.org'
# source ENV['GEM_MIRROR'] || "https://rubygems.org"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'tzinfo-data', '~> 1.2.2', platforms: [:mingw, :mswin, :x64_mingw]
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.5'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 3.0.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.1'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 4.1.1'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '~> 5.0.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.1', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# Gems added by Commverge
gem 'mysql2', '~> 0.4.4'
gem 'devise', '~> 4.2.0'
gem 'pundit', '~> 1.1.0'
gem 'omniauth', '~> 1.3.1'
#gem 'omniauth-oauth2', '~> 1.3.1'
gem 'omniauth-oauth2', '~> 1.4.0'
gem 'omniauth-facebook', '~> 3.0.0'
gem 'omniauth-google-oauth2', '~> 0.4.1'
gem 'omniauth-linkedin-oauth2', '~> 0.1.5'
gem 'grape', '~> 0.15.0'
gem 'grape-entity', '~>0.4.8'
gem 'grape-swagger', '~> 0.10.5'
gem 'grape-swagger-rails', '~> 0.2.1'
gem 'simple_form', '~> 3.2.1'
gem 'rails_layout', '~> 1.0.29'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sidekiq', '~> 4.1.4'
gem 'sinatra', '~> 1.4.7', require: false
gem 'slim', '~> 3.0.7'
gem 'carrierwave', '~> 0.11.2'#, github:'carrierwaveuploader/carrierwave'
gem 'rack-cors', '~> 0.4.0', :require => 'rack/cors'
gem 'cocoon', '~> 1.2.9'
gem 'ffi-rzmq', '~> 2.0.4'
gem 'http_accept_language', '~> 2.0.5'
gem 'devise-i18n', '~> 1.1.0'

gem 'dotenv-rails', '~> 2.1.1'

# deploy
group :production do
  gem 'mina', '~> 0.3.8'
  gem 'puma', '~> 3.4.0'
  gem 'mina-puma', '~> 0.3.1', require: false
  gem 'mina-sidekiq', '~> 0.4.1', require: false
end

# zip file
gem 'rubyzip', '~> 1.2'

# spreadsheet handling tool
gem 'roo', '~> 2.5'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 9.0', '>= 9.0.3'
  gem 'rspec-rails', '~> 3.4', '>= 3.4.2'
  gem 'factory_girl_rails', '~> 4.7'
  gem 'spring-commands-rspec', '~> 1.0.4' #加速测试
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'guard', '~> 2.14.0' #修改文件自动跑测试的工具
  gem 'guard-rspec', '~> 4.7.2'
  gem 'guard-bundler', '~> 2.1.0'
  gem "rubycritic", '~> 2.9.2', :require => false
end

group :test do
  gem 'faker', '~> 1.6', '>= 1.6.3'
  gem 'capybara', '~> 2.7', '>= 2.7.1'
  gem 'launchy', '~> 2.4', '>= 2.4.3'
  gem 'selenium-webdriver', '~> 2.53'
end

group :development do
  gem 'pry', '~> 0.10.3'
  gem 'pry-rails', '~> 0.3.4'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 1.7.2'
  gem 'better_errors', '~> 2.1.1'
  gem 'quiet_assets', '~> 1.1.0'
end
